### ISSUE TITLE
Full Stack projektin katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [aarnipavlidi/Biostack#12]
# Full Stack projektin katselmointi

Terve @aarnipavlidi! Tässä lyhyt katselmointi Full Stack kurssin projektistasi. Katselmoinnissa esitetyt kommentit ovat parannusehdotuksia, joita voit _halutessasi_ ottaa huomioon tässä tai tulevissa projekteissasi. Mitään muutoksia tähän projektiin ei siis ole pakko tehdä suoritusmerkintää varten.

## Käytettävyys

Avasin sovelluksen Expo-sovelluksen kautta. Pikaisen käytön perusteella sovelluksella on erittäin tyylikäs ja intuitiivinen käyttöliittymä, loistavaa työtä! 🥇 Expo-sovelluksen kautta testaaminen osoittautui kuitenkin hieman hankalaksi käyttöliittymän epäresponsiivisuuden takia (varmasti Expo-sovelluksen ongelma), joten tutustuin osaan toiminallisuuksista README:n kautta. Toiminallisuus vaikuttaa erittäin viimeistellyltä ja ammattimaiselta.

## Koodi

- React Native -puolen koodi on selkeästi organisoitua, hyvä!
- Koko projektin koodia piinaava ongelma on aivan liian suuri määrä kommentteja. Tätä pidetään niin kutsuttana "koodihajuna", eli merkkinä koodin huonosta laadusta. Kommenttien pitäisi ainoastaan ilmaista sitä, mitä koodin avulla ei pysty ilmaisemaan. Ja yleensä jos koodi ei jotain asiaa pysty selkeästi ilmaisemaan, niin sitä tulee parantaa. Esim. [tämä](https://github.com/aarnipavlidi/Biostack/blob/main/App.js#L8) kommentti:

  ```js
  import createApolloClient from './src/utils/apolloClient'; // Import "createApolloClient" function content for this component usage.
  ```

  Koodi ilmaisee valmiiksi täsmälleen kommentin kuvauksen, jolloin kommentti vain heikentää koodin luettavuutta.

- Hooks-hakemistossa on paljon loistavia hook-abstraktioita. Nämä parantavat komponenttien koodin luettavuutta ja ylläpidettävyyttä
- Käyttöliittymän teema on konfiguroitu ja tyylien määrittelyssä käytetään konfiguraatioita, hienoa!
- GraphQL-koodi on organisoitu hyvin. Kyselyissä on tosin hieman toisteellisuutta. [Fragmentit](https://graphql.org/learn/queries/#fragments) auttavat tässä
- [Tämä](https://github.com/aarnipavlidi/Biostack/blob/main/src/utils/apolloClient.js#L16) voisi ehkä tulla ympäristömuuttujasta?
- Jos token on merkkijono niin [tätä](https://github.com/aarnipavlidi/Biostack/blob/main/src/utils/authStorage.js#L22) JSON-serialisaatiota ei tarvita
- Backend-koodia on myös organisoitu jonkin verran. Tosin GraphQL-skeeman määrittely yhdessä tiedostossa tekee koodista melko sekavaa ja vaikeasti ylläpidettävää. Esim. [tässä](https://github.com/Kaltsoon/rate-repository-api/tree/master/src/graphql) on yksi tapa organisoida GraphQL-skeeman määrittely
- Merkkijonomuotoisia vakiarvoja kuten [tämä](https://github.com/aarnipavlidi/Biostack-backend/blob/main/index.js#L405) kannattaa välttää mm. kirjoitusvirheistä aiheutuvien bugien vähentämiseksi ja koodin refaktoroinnin helpottamiseksi. Käytä sen sijaan vakiomuuttujia:

  ```js
  const PubSubEvent = {
    PRODUCT_ADDED: 'PRODUCT_ADDED',
    // ...
  };

  // ...
  pubsub.publish(PubSubEvent.PRODUCT_ADDED, /* ... */);
  ```

- Mongoose hoitaa [Object id -tyyppimuunnokset](https://github.com/aarnipavlidi/Biostack-backend/blob/main/index.js#L503) puolestasi

## Kokonaisuus

Todella kattava React Native -projekti, jossa on paljon mielekästä toiminallisuutta ja tyylikäs käyttöliittymä. Projektin koodi on suurimmilta osin erittäin laadukasta. Koodin aivan liiallinen kommentointi ja backendin GraphQL-skeeman määrittely yhdessä tiedostossa ovat tärkeimmät parannuskohteet. Nämä parannuskohteet on kuitenkin helppo korjata kun muilta osin koodi on erittäin hyvällä mallilla. Loistavaa työtä!

**Comment by aarnipavlidi** [comment]
Hei @Kaltsoon,

Kiitos palautteesta, mahdollisesti jatkan tätä projektia opinnäytetyötä varten niin korjaan nuo esitetyt muutokset! 😊
